### ISSUE TITLE
More information on how to change lab style

### ISSUE THREAD

**Issue by jhrcook** [jgburet/jumpy-sublime#3]
Can you provide more information on how to adjust the styling of the labels? I'm not sure where to find the CSS file to edit? I'm using the `"Packages/Color Scheme - Default/Mariana.sublime-color-scheme"` color scheme, if that helps.

Thanks,
Josh

**Comment by jgburet** [comment]
Thanks for your interest in this package.

Before answering, I tried to customize the labels by changing the background color. However it seems like there is a bug in ST and some characteristics are not impacted such as the font size and the background color: https://github.com/sublimehq/sublime_text/issues/2935

You can still try by yourself if you want:
Open palette >`Install Package` > "Package Resource Viewer"
Open palette > "Package Resource Viewer : Extract package" > "Theme Default"
Preferences > Browse packages > Color Scheme - Default
Duplicate the file for your scheme, don't close the file explorer
Open palette > "UI: Select color scheme" > find your copy
From the file explorer open the copy with ST
In the `"globals"` dictionary, add `, "phantom_css": "#jumpy div.label {  }"`
This way you can mess with your style and come back any time to a clean state :)

Since I don't know how long it might take for ST team to fix the bug, I'm going to allow the user to define the css of the labels directly in his settings instead of in his color scheme. I might get that released by next week. Does that sound okay to you?

**Comment by jhrcook** [comment]
Thanks for producing the package and responding to the issue so quickly. 

Personally, I would prefer to be able to modify the labels in the settings (vs. in the color scheme) since I like to use syntax specific settings. In case it is relevant, I would like to increase the font size and change the font family of the labels.

**Comment by jgburet** [comment]
It was easier than I expected.
I made a new release https://github.com/jgburet/jumpy-sublime/releases/tag/0.2.0
Just give a bit of time to the package control to be notified and make the new version available. You should have it next time you reopen ST tomorrow morning.

**Comment by jgburet** [comment]
Any more help required here @jhrcook ?

**Comment by jhrcook** [comment]
Works great! Thank you!
